//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACES_Search_Terms
    {
        public long LACES_Search_Terms_id { get; set; }
        public string SubjectArea { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateSearched { get; set; }
    }
}
namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprovedProvider
    {
        public long ID { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationStreetAddress { get; set; }
        public string OrganizationCity { get; set; }
        public string OrganizationState { get; set; }
        public string OrganizationZip { get; set; }
        public string OrganizationCountry { get; set; }
        public string OrganizationPhone { get; set; }
        public string OrganizationFax { get; set; }
        public string OrganizationWebSite { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantPosition { get; set; }
        public string ApplicantPhone { get; set; }
        public string ApplicantFax { get; set; }
        public string ApplicantEmail { get; set; }
        public string Password { get; set; }
        public string OrganizationNature { get; set; }
        public Nullable<bool> LegallyConstituted { get; set; }
        public string LegallyConstitutedDescription { get; set; }
        public Nullable<bool> RegionallyAccredited { get; set; }
        public string RegionallyAccreditedDescription { get; set; }
        public Nullable<bool> ProfessionalAssociation { get; set; }
        public Nullable<bool> FederalOrganization { get; set; }
        public Nullable<bool> StateOrganization { get; set; }
        public Nullable<bool> LocalGovernmentAgency { get; set; }
        public Nullable<bool> OrganizationUnderstandLACES { get; set; }
        public Nullable<bool> CoursesOfferedAsLACES { get; set; }
        public Nullable<bool> AgreeToDesignateCoursesAsLACES { get; set; }
        public Nullable<bool> FollowLACESGuidelines { get; set; }
        public Nullable<bool> AgreeToFollowLACESGuidelines { get; set; }
        public string HowDeterminesCourses { get; set; }
        public Nullable<bool> OrganizedAndSystematicProcess { get; set; }
        public string DescribeProcedures { get; set; }
        public Nullable<int> WrittenLearningObjectives { get; set; }
        public string DescribeCourse1 { get; set; }
        public string DescribeCourse2 { get; set; }
        public Nullable<bool> AgreeToDevelopWrittenObjectives { get; set; }
        public string HowDeterminePersonnelDevelopCourses { get; set; }
        public string HowDeterminePersonnelDeliverCourses { get; set; }
        public Nullable<bool> EvaluateCoursesToEnsureProgramContent { get; set; }
        public string ProceduresSurveysEvaluationInstrumentsOrganizationUses { get; set; }
        public Nullable<bool> FollowLACESCriteriaToUseOnlyMaterials { get; set; }
        public string HowOrganizationAssessParticipantAttainment { get; set; }
        public Nullable<int> CoursesEvaluatedByParticipants { get; set; }
        public Nullable<int> EvaluateProgramsInwaysOtherThanByParticipants { get; set; }
        public string ExplainMethodsInwaysOtherThanByParticipants { get; set; }
        public Nullable<bool> OrganizationProvideCertificates { get; set; }
        public string HowOrganizationProvideConfirmation { get; set; }
        public Nullable<bool> AgreeToMaintainCompleteAttendanceRecords { get; set; }
        public string DescribeOrganizationsRecordkeepingSystem { get; set; }
        public Nullable<bool> OrganizationHasAnInternalReviewProcess { get; set; }
        public string DescribeWrittenPolicyOrCriteriaReviewProcess { get; set; }
        public string AgreementOrganizationName { get; set; }
        public string AuthorizerName { get; set; }
        public string AuthorizerPosition { get; set; }
        public Nullable<System.DateTime> AuthorizerDate { get; set; }
        public string AuthorizerPhone { get; set; }
        public string AuthorizerEmail { get; set; }
        public System.DateTime ApplicationSubmissionDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> DeferralDate { get; set; }
        public Nullable<System.DateTime> DenialDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> WithdrawalDate { get; set; }
        public Nullable<System.DateTime> NextRenewalDate { get; set; }
        public string ShortDescription { get; set; }
        public string LearningOutcome { get; set; }
        public string CourseOutline { get; set; }
        public Nullable<bool> DevelopInternalReview { get; set; }
        public Nullable<bool> KeepAllMaterials { get; set; }
        public Nullable<System.DateTime> ApplicationReceivedDate { get; set; }
        public Nullable<System.DateTime> CommiteeApprovedDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string Payment { get; set; }
        public string YearMonitored { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> isPaymentExempt { get; set; }
    }
}
namespace Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParticipantCource
    {
        public long ParticipantID { get; set; }
        public long CourseID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
namespace Utility
{
    using System;
    
    public partial class LACES_VisualizationNewProviders_Result
    {
        public Nullable<int> providercount { get; set; }
        public string ProviderType { get; set; }
    }
}
namespace Utility
{
    using System;
    
    public partial class LACES_VisualizationSubjectByDate_Result
    {
        public Nullable<int> subjectcount { get; set; }
        public string declaration { get; set; }
    }
}
namespace Utility
{
    using System;
    
    public partial class LACES_VisualizationSubjectByLocation_Result
    {
        public Nullable<int> locationcount { get; set; }
        public string StateProvince { get; set; }
    }
}
